# The URL the site will be built for
base_url = "https://my-radion-blog-1lxr.vercel.app/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

title = "My Awsome Blog"
description = "A elegant light and dark blog for Zola"
generate_feeds = true

taxonomies = [
    # You can enable/disable RSS
    { name = "categories", feed = true },
    { name = "tags", feed = true },
]

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

# The theme(s) to use for code highlighting.
# For more themes, see: https://www.getzola.org/documentation/getting-started/configuration/#syntax-highlighting
highlight_theme = "css"
highlight_themes_css = [
  { theme = "one-dark", filename = "syntax/syntax-theme-dark.css" },
  { theme = "gruvbox-dark", filename = "syntax/syntax-theme-light.css" },
]

# This determines whether to insert a link for each header like the ones you can see on this site if you hover over
# a header.
# The default template can be overridden by creating an `anchor-link.html` file in the `templates` directory.
# This value can be "left", "right", "heading" or "none".
# "heading" means the full heading becomes the text of the anchor.
# See "Internal links & deep linking" in the documentation for more information.
insert_anchor_links = "heading"

build_search_index = true

[search]
index_format = "elasticlunr_json"

[extra]
# Put all your custom variables here
toc = true
author = "Micah Kepe"
github = "https://github.com/micahkepe/radion"
fediverse.creator = "@username@my.instance.example.com"
fediverse.rel_me = "https://my.instance.example.com/@username"
mastodon = "https://my.instance.example.com/@username"


radion_menu = [
    { url = "$BASE_URL", name = "Home" },
    { url = "$BASE_URL/categories", name = "Categories" },
    { url = "$BASE_URL/tags", name = "Tags" },
    { url = "https://google.com", name = "Google" },
]
radion_title = "My Example Site"

# Nicer codeblocks with copy to clipboard
codeblock = true

# Enable MathJax support
latex = true

# Enable search bar
enable_search = true

# Light/Dark Mode set
theme = "toggle" # options: {light, dark, auto, toggle}

# Whether to display favicon
favicon = true

# Giscus comment support
comments = true
giscus_repo = "micahkepe/radion"
giscus_repo_id = "R_kgDONK7lCQ"
giscus_data_category_id = "DIC_kwDONK7lCc4CnfXf"

# Post revision history
revision_history = true
blog_github_repo_url = "https://github.com/micahkepe/radion"
